services:
  - type: web
    name: rag-with-lcg
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
